import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "../components/Navbar";
import ClientRoot from "../components/ClientRoot";
import { LangProvider } from "../components/LangProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <LangProvider>
          <ClientRoot>
            <Navbar />
            {children}
          </ClientRoot>
        </LangProvider>
      </body>
    </html>
  );
}
